### ISSUE TITLE
Might be handy to replace bookmark location

### ISSUE THREAD

**Issue by DiegoFleitas** [skrysmanski/chrome-separators#3]
If you replace the source of the bookmark as if it was a bookmarklet you can get away with the separators not redirecting you when clicked, like so

![image](https://user-images.githubusercontent.com/15369935/74095151-6fa32200-4acb-11ea-8102-8a40dcdac2da.png)

**Comment by skrysmanski** [comment]
It's a good idea. Unfortunately, this doesn't work as Chrome uses the location to determine icon for the bookmark. And with this solution you'd always get the default bookmark icon (the globe).
