### ISSUE TITLE
Horizontal spacer not working

### ISSUE THREAD

**Issue by Chaprnks** [skrysmanski/chrome-separators#5]
Vertical spacer works perfectly, but I can't seem to get the horizontal spacer to work at all. It just shows the URL title in the bookmarks folder, without a favicon

**Comment by Teezton** [comment]
Yes indeed! The icon seems wrong @skrysmanski.

![0](https://user-images.githubusercontent.com/5905860/101754864-1da4a180-3acc-11eb-9f2a-6119316b4008.png)

**Comment by connoro7** [comment]
Looks like this is fixed in #2, but it also looks like it won't be merged to prod:

> "While I generally have nothing against this change, I think I made the icon for the horizontal separator intentionally blank (if I can remember correctly)." - @skrysmanski

**Comment by skrysmanski** [comment]
Just to make sure:

Instead of this:

![without](https://user-images.githubusercontent.com/914747/126894528-4011b20c-a9e1-456f-9095-b28482684fbc.png)

You want this:

![with](https://user-images.githubusercontent.com/914747/126894534-46e25e99-76a0-400a-8501-a4d5768e4023.png)

Correct?

**Comment by buismaarten** [comment]
This can't be intentional right?

![image](https://user-images.githubusercontent.com/16333228/127040542-df69e620-51f3-4843-bee6-b20b7fe75743.png)

**Comment by skrysmanski** [comment]
@buismaarten Yes, it is - to have an empty favicon.

**Comment by skrysmanski** [comment]
Closing this due to a lack of feedback.
